label: 'GA4GH :: SchemaBlocks'
tagline: 'An Initiative by Members of the Global Alliance for Genomics and Health'
description: |
  SchemaBlocks is a cross-workstream project of the Global Alliance for Genomics & Health
keywords: genomics, cloud, Beacon, DNA, sharing, GA4GH
site_domain_name: schemablocks.org
url: 'https://schemablocks.org'
google_search_code: |
  <script async src="https://cse.google.com/cse.js?cx=008117828495027240668:yh9utjhmnjo"></script>
  <div class="gcse-searchbox-only"></div>
baseurl: ""
site_parent_link: 'https://ga4gh.org'
github_organisation: ga4gh-schemablocks

# instructions for processing specific directories

include:        # usually only pages in / and /_posts are "seen" => processed
  - categories  # contains landing pages for each category
  - tags        # contains landing pages for each tag
  - schemas

# Collections are used to organise pages into logical groups; these do not need
# to have a relation to the "categories", though this is highly recommended
# Collection directories reside in "/collections_dir/_(collection name)".

collections:
  schemas:
    output: true
    permalink: /schemas/:path/
  standards:
    output: true
    permalink: /standards/:path/
  people:
    output: true
    permalink: /people/:path/
  doc:
    output: true
    permalink: /doc/:path/
collections_dir: pages  # optional; here, all collections are inside "/pages"

# navigation blocks can be used to separate different categories and add e.g.
# external link block(s), in combination with a properly modified layout

nav_cat_blocks: # comma-separated "label,type,label_visibility"
  General: 'General,categories,hide'
  related_sites: 'Related Sites,related_sites,show'
  github_projects: 'Github Projects,github_projects,show'

General:
  about: 'About {S}[B]'
  news: News
  people: Participants
  standards: 'Standards'
  schemas: 'Schemas'
  howto: 'Examples, Guides & FAQ'
  minutes: 'Meeting minutes'
  contact: Contacts

categories-date-sorted:
  - news
  - minutes

tags-date-sorted:
  - press
  - news

related_sites:
  GA4GH: 'http://www.ga4gh.org'
  'GA4GH::Discovery': 'http://ga4gh-discovery.github.io'
  'ELIXIR Beacon': 'http://ga4gh-beacon.github.io'
  Phenopackets: 'http://github.com/phenopackets'
  'GA4GH::CLP': 'http://ga4gh-cp.github.io'
  'GA4GH::GKS': 'http://ga4gh-gks.github.io'
  'Beacon<span style="color: red; font-weight: 800;">+</span>': 'http://beacon.progenetix.org/ui/'

github_projects:
  'SchemaBlocks': 'http://github.com/ga4gh-schemablocks/'
  'ELIXIR Beacon': 'https://github.com/ga4gh-beacon/'

# tag_cloud items

cloud_tags:
  - Beacon
  - CP
  - Discovery
  - FAQ
  - GA4GH
  - GKS
  - MME
  - code
  - admins
  - contacts
  - contributors
  - dates
  - developers
  - documentation
  - identifiers
  - issues
  - howto
  - leads
  - news
  - phenopackets
  - press
  - tools
  - website
  - playground      # sb_status
  - proposed        # sb_status
  - implemented     # sb_status
  - core            # sb_status

# additional Jekyll instructions

plugins:
 - jekyll-seo-tag
type: website
show_downloads: true
future: true
safe: false
navigation_max_items: 4 # number of shown links in current category
emptyArray: []          # dummy element for array initialisation
