site_name: 'Genome Standards and Schema Blocks'
site_description: 'Standards Collection Website of the GA4GH community'
site_author: Michael Baudis
copyright: '&copy; Copyright 2023 GA4GH Contributors'
repo_name: 'schemablocks.github.io'

repo_url: https://github.com/ga4gh-schemablocks/ga4gh-schemablocks.github.io
edit_uri: edit/main/docs/

###############################################################################

nav:
  - 'Home': index.md
#  - News: news
#  - About SchemaBlocks: schemablocks-principles.md
  - Standards & Practices: standards-recommendations
    # - Genome Coordinates: standards-recommendations/genome-coordinates
    # - Dates & Times: standards-recommendations/dates-times
    # - Identifiers: standards-recommendations/identifiers
  - Schemas: schema_pages
  - Contacts: contacts
  - '{S}[B] Legacy Site &#8599;': https://schemablocks.genomestandards.org
  - Beacon Project &#8599;: https://beacon-project.io
  - Phenopackets &#8599;: https://phenopackets.org

###############################################################################

markdown_extensions:
  - toc:
      toc_depth: 2-3
      permalink: true
  - admonition
  - attr_list
  - footnotes
  - md_in_html
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.magiclink:
      hide_protocol: true
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.saneheaders
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - mdx_gh_links:
      user: hCNV
      repo: hcnv.github.io
  - pymdownx.emoji:
        emoji_index: !!python/name:materialx.emoji.twemoji
        emoji_generator: !!python/name:materialx.emoji.to_svg
        options:
          custom_icons:
            - extra/.icons

###############################################################################

theme:
  name: material
  palette:
    primary: light blue
    # scheme: slate
  favicon: img/logo-schemablocks-no-text-50x50.png
  logo: img/logo-GA4GH-white-text-670x160.png
  icon:
    repo: fontawesome/brands/github-alt
    admonition:
      example: octicons/list-ordered-24
  features:
    - content.tabs.link
    - search.highlight
    - search.share
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - toc.integrate
  custom_dir: extra
      
plugins:
    - search
    - macros

extra:
  excerpt_separator: <!--more-->
  blog_list_length: 100
  social:
    # - icon: fontawesome/brands/twitter 
    #   link: https://twitter.com/progenetix
    - icon: fontawesome/brands/github 
      link: https://github.com/ga4gh-schemablocks
extra_css:
  - css/theme_overrides.css
